export const images = {
  auth: {
    google: '/assets/auth/google.svg',
    facebook: '/assets/auth/facebook.svg',
    apple: '/assets/auth/apple.svg',
  },
  nav: {
    searchLine: "/assets/nav/search-line.svg",
    mapPin: "/assets/nav/map-pin-line.svg",
    lifebuoy: "/assets/nav/lifebuoy-line.svg",
    global: "/assets/nav/global-line.svg",
    logo: "/assets/nav/logo-primary.svg",
    listCheck: "/assets/nav/list-check.svg",
    searchWhite: "/assets/nav/search-white.svg",
    heart: "/assets/nav/heart-line.svg",
    cart: "/assets/nav/cart-line.svg",
    user: "/assets/nav/user-line.svg",
  },
  hero: {
    banner: "/assets/hero/banner.png",
    banners: [
      "/assets/hero/banner.png",
      "/assets/categories/furniture.png",
      "/assets/categories/electronics.png",
      "/assets/categories/decor.png",
      "/assets/categories/accessories.png",
    ],
    newArrivalsCard: "/assets/hero/new-arrivals-card.png",
    priceTag: "/assets/hero/price-tag.svg",
    alarm: "/assets/hero/alarm.svg",
    computer: "/assets/hero/computer.svg",
    tshirt: "/assets/hero/tshirt.svg",
    sofa: "/assets/hero/sofa.svg",
    hammer: "/assets/hero/hammer.svg",
    lightbulb: "/assets/hero/lightbulb.svg",
  },
  features: {
    delivery: "/assets/features/delivery.svg",
    quality: "/assets/features/quality.svg",
    support: "/assets/features/support.svg",
  },
  categories: {
    electronics: "/assets/categories/electronics.png",
    furniture: "/assets/categories/furniture.png",
    accessories: "/assets/categories/accessories.png",
    decor: "/assets/categories/decor.png",
    fashion: "/assets/categories/fashion.png",
  },
  categoriesModal: {
    star: "/assets/categories/star-line.svg",
    items: [
      "/assets/categories/modal/01.png",
      "/assets/categories/modal/02.png",
      "/assets/categories/modal/03.png",
      "/assets/categories/modal/04.png",
      "/assets/categories/modal/05.png",
      "/assets/categories/modal/06.png",
      "/assets/categories/modal/07.png",
      "/assets/categories/modal/08.png",
      "/assets/categories/modal/09.png",
      "/assets/categories/modal/10.png",
      "/assets/categories/modal/11.png",
      "/assets/categories/modal/12.png",
      "/assets/categories/modal/13.png",
      "/assets/categories/modal/14.png",
      "/assets/categories/modal/15.png",
      "/assets/categories/modal/16.png",
      "/assets/categories/modal/17.png",
    ],
  },
  newArrivals: {
    speaker: "/assets/new-arrivals/speaker.png",
    earbuds: "/assets/new-arrivals/earbuds.png",
    chair: "/assets/new-arrivals/chair.png",
  },
  featured: {
    speaker: "/assets/featured/speaker.png",
    chair: "/assets/featured/chair.png",
    headphones: "/assets/featured/headphones.png",
  },
  promo: {
    banner: "/assets/promo/banner.png",
  },
  footer: {
    logo: "/assets/footer/logo.svg",
    mail: "/assets/footer/mail.svg",
    appStore: "/assets/footer/app-store.svg",
    googlePlay: "/assets/footer/google-play.svg",
    facebook: "/assets/footer/facebook.svg",
    instagram: "/assets/footer/instagram.svg",
    tiktok: "/assets/footer/tiktok.svg",
    youtube: "/assets/footer/youtube.svg",
    linkedin: "/assets/footer/linkedin.svg",
    twitter: "/assets/footer/twitter.svg",
    trust1: "/assets/footer/trust-1.png",
    trust2: "/assets/footer/trust-2.png",
    trust3: "/assets/footer/trust-3.png",
    trust4: "/assets/footer/trust-4.png",
    trust5: "/assets/footer/trust-5.png",
    applePay: "/assets/footer/apple-pay.svg",
    mastercard: "/assets/footer/mastercard.svg",
    visa: "/assets/footer/visa.svg",
    paypal: "/assets/footer/paypal.svg",
    tabby: "/assets/footer/tabby.svg",
    tamara: "/assets/footer/tamara.png",
    tamaraIcon: "/assets/footer/tamara-icon.svg",
    googlePay: "/assets/footer/google-pay.svg",
    divider: "/assets/footer/divider.svg",
    compliance: "/assets/footer/compliance.png",
  },
  shared: {
    arrowRight: "/assets/shared/arrow-right.svg",
    arrowLeft: "/assets/shared/arrow-left.svg",
    heartLine: "/assets/shared/heart-line.svg",
    heartFill: "/assets/shared/heart-fill.svg",
    ratingStar: "/assets/shared/rating-star.svg",
    addLine: "/assets/shared/add-line.svg",
  },
  orders: {
    empty: "/assets/orders/empty-orders.svg",
  },
  about: {
    hero: "/assets/about/hero.png",
    shoppingCart: "/assets/about/shopping-cart.png",
  },
} as const
